// Single source of truth for the app version. Keep in lockstep with the latest
// GitHub release, api.py FastAPI version, and ui/package.json on every release.
export const VERSION = "1.7.1";

export const AGENTS = [
  { id: "coordinator",        label: "Coordinator",         icon: "◈", color: "#9A6C00", focus: "Delegation & orchestration of all agents", role: "Reads every message, runs keyword routing first, falls back to phi4-mini for ambiguous queries. Routes to the correct specialist in under 1 second for known keywords.", keywords: ["any message — it decides where it goes"], phase: 4 },
  { id: "python_dev",         label: "Python Dev",           icon: "λ", color: "#C48808", focus: "Python code, scripts, automation, debugging, FastAPI, asyncio", role: "Writes complete working Python code. Give it a specific task with inputs, outputs, and edge cases — it returns runnable code you can copy and execute.", keywords: ["python","flask","fastapi","script","automation","pip"], phase: 3 },
  { id: "web_dev",            label: "Web Dev",              icon: "⊹", color: "#C2410C", focus: "JavaScript, TypeScript, React, Next.js, Vue, Node.js, CSS", role: "Full-stack web specialist. Writes React components, TypeScript types, Node.js APIs, and Tailwind layouts. Handles hooks, async state, and build tooling.", keywords: ["javascript","typescript","react","nextjs","vue","nodejs","npm","css","html"], phase: 36 },
  { id: "dotnet_dev",         label: ".NET Dev",             icon: "⬡", color: "#7C3AED", focus: ".NET, C#, ASP.NET Core, Blazor, Entity Framework, xUnit", role: "Expert in the .NET ecosystem. Writes C# classes, ASP.NET Core APIs, Blazor components, and EF Core queries. Handles DI, async patterns, and testing.", keywords: ["blazor","dotnet","c#","csharp","entity framework","asp.net","nuget"], phase: 36 },
  { id: "devops",             label: "DevOps",               icon: "⚙", color: "#047857", focus: "Docker, Kubernetes, CI/CD, GitHub Actions, Bash, Linux admin", role: "Infrastructure and deployment specialist. Writes Dockerfiles, Compose configs, GitHub Actions pipelines, and systemd units. Runs real docker and systemctl commands.", keywords: ["docker","kubernetes","ci/cd","github actions","bash","deploy","pipeline"], phase: 36 },
  { id: "data_analyst",       label: "Data Analyst",         icon: "∑", color: "#1E5A8A", focus: "pandas, SQL, NumPy, matplotlib, seaborn, statistics, data cleaning", role: "Data analysis specialist. Writes pandas transformations, SQL queries, and visualization code. Handles EDA, data cleaning, and statistical summaries.", keywords: ["pandas","sql","dataframe","csv","matplotlib","statistics","data analysis"], phase: 36 },
  { id: "writer",             label: "Writer",               icon: "¶", color: "#6D28D9", focus: "Technical docs, READMEs, blog posts, commit messages, editing", role: "Technical writing specialist. Writes READMEs, API docs, blog posts, and commit messages. Also edits and proofreads existing text for clarity and conciseness.", keywords: ["documentation","readme","technical writing","blog post","proofread","edit"], phase: 36 },
  { id: "ai_ml",              label: "AI & ML",              icon: "∴", color: "#BE185D", focus: "AI concepts, ML frameworks, PyTorch, TensorFlow, LLMs, embeddings", role: "Explains AI and ML concepts clearly. Helps with model architecture, training pipelines, and working with local LLMs like Ollama.", keywords: ["tensorflow","pytorch","neural network","machine learning","llm","embedding"], phase: 3 },
  { id: "it_networking",      label: "IT & Networking",      icon: "⊃", color: "#15803D", focus: "Wi-Fi, routers, network diagnostics, DNS, SSH, ports, Linux networking", role: "Networking and sysadmin specialist. Runs real commands — ping, ip addr, nslookup — and gives specific, actionable advice based on real output.", keywords: ["wifi","router","network","dns","ip address","ssh","port","vpn"], phase: 3 },
  { id: "terse",              label: "Terse",                icon: "▸", color: "#9A6C00", focus: "One-line answers: commands, syntax, code snippets", role: "Fast lookup agent. Answers commands, syntax, and quick definitions in one line. No explanation, no analogies — just the answer.", keywords: ["give me the command","command for","syntax for","one line","just give me"], phase: 5 },
  { id: "knowledge_learning", label: "Knowledge",            icon: "§", color: "#1E5A8A", focus: "IT fundamentals, learning concepts, tutorials, explanations, study plans", role: "General knowledge and learning agent. Explains complex concepts clearly, corrects wrong analogies directly, and saves lessons to memory.", keywords: ["explain","how does","tutorial","teach me","what is","learn"], phase: 3 },
];

// ── Build phase history (all completed releases) ───────────────────────────────
export const BUILD_PHASES = [
  // ── v0.1  Foundation ──────────────────────────────────────────
  {
    id: 1, version: "v0.1.0", date: "Dec 15, 2025",
    label: "Phase 1",  title: "Foundation Audit", color: "#15803D", status: "done",
    summary: "Environment bootstrapped: LangGraph v1.0, phi4-mini via Ollama, shared AgentState schema.",
    steps: ["LangGraph v1.0 environment created", "phi4-mini running via Ollama", "Shared AgentState TypedDict defined", "Config settings in place"],
  },
  {
    id: 2, version: "v0.1.1", date: "Dec 20, 2025",
    label: "Phase 2",  title: "Agent Architecture", color: "#9A6C00", status: "done",
    summary: "Project structure organized, coordinator drafted, hybrid keyword + LLM routing planned.",
    steps: ["Organized project directories", "Coordinator drafted", "Hybrid routing logic planned", "AgentState schema defined"],
  },
  {
    id: 3, version: "v0.1.2", date: "Jan 5, 2026",
    label: "Phase 3",  title: "Specialist Agents", color: "#C2410C", status: "done",
    summary: "5 specialist agents implemented and wired: IT & Networking, Python Dev, Blazor Dev, AI & ML, Knowledge & Learning.",
    steps: ["IT & Networking agent", "Python Dev agent", "Blazor Dev agent", "AI & ML agent", "Knowledge & Learning agent"],
  },

  // ── v0.2  Core Systems ────────────────────────────────────────
  {
    id: 4, version: "v0.2.0", date: "Jan 12, 2026",
    label: "Phase 4",  title: "Coordinator + Routing", color: "#7E3F8F", status: "done",
    summary: "Coordinator finalized with force_agent field wired end-to-end; hybrid keyword → LLM fallback routing live.",
    steps: ["Hybrid router: keyword + LLM fallback", "force_agent field wired end-to-end", "API + State + Coordinator all respect override", "Task Queue respects agent selection"],
  },
  {
    id: 5, version: "v0.2.1", date: "Jan 20, 2026",
    label: "Phase 5",  title: "Interfaces & Memory", color: "#0F766E", status: "done",
    summary: "FastAPI server on port 8000, React Mission Control UI, SQLite + nomic-embed-text semantic memory.",
    steps: ["FastAPI server on port 8000", "React Mission Control app", "SQLite + nomic-embed-text embeddings", "memory_filter.py blocks fluff before embedding", "clean_content() strips fluff openers", "Duplicate detection via Dice coefficient", "DB wiped clean — 48 noise entries removed", "Memory wired into all agents"],
  },
  {
    id: 6, version: "v0.2.2", date: "Feb 3, 2026",
    label: "Phase 6",  title: "Reliability", color: "#BE185D", status: "done",
    summary: "Concurrency hardened with asyncio.Lock; sequential worker; self-restarting task loop.",
    steps: ["asyncio.Lock confirmed safe", "Sequential worker design", "Self-restarting worker", "reset_orphaned_running_tasks()", "asyncio.Event cleaner pattern"],
  },

  // ── v0.3  Integration ─────────────────────────────────────────
  {
    id: 7, version: "v0.3.0", date: "Mar 15, 2026",
    label: "Phase 7",  title: "Model Overview", color: "#047857", status: "done",
    summary: "First health report generated (Mar 15 2026): 10 memories, 4 tasks, 8 agents wired.",
    steps: ["First report: March 15 2026", "10 memories, 4 tasks, 8 agents wired", "Mushroom Farmer project tracked", "ModelOverview.py generates health report"],
  },
  {
    id: 8, version: "v0.3.1", date: "Mar 22, 2026",
    label: "Phase 8",  title: "Personalization + Cleanup", color: "#C2410C", status: "done",
    summary: "User profile (identity, style, mind, dont) injected into all agents; project cleanup and ghost DB deletion.",
    steps: ["user_profile.py — identity/style/mind/dont", "Profile injected into all agents", "force_agent 422 error fixed", "Task Queue agent selection wired", "Project cleanup: .bak archived, scripts/ folder", "Ghost DB deleted, docs/ established", "requirements.txt generated"],
  },
  {
    id: 9, version: "v0.3.2", date: "Mar 30, 2026",
    label: "Phase 9",  title: "Performance + Machine", color: "#0E7490", status: "done",
    summary: "RTX 2050 GPU driver installed; LLM fallback removed from router; response time 361 s → 56 s (6×).",
    steps: ["GPU driver installed (RTX 2050)", "LLM fallback removed from router — 17/17 keyword tests pass", "Model switched to llama3:8b-instruct-q3_K_M (4GB fits VRAM)", "OLLAMA_MAX_LOADED_MODELS=1 prevents VRAM conflict", "Response time: 361s → 56s (6× improvement)", "Aliases added: ai-start · ai-ui · ai-stop · ai-logs", "Unnecessary services disabled (cups, avahi, ModemManager)"],
  },

  // ── v0.4  Optimization & Routing ─────────────────────────────
  {
    id: 10, version: "v0.4.0", date: "Apr 7, 2026",
    label: "Phase 10", title: "Audit & Simplification", color: "#047857", status: "done",
    summary: "Usage audit: 3 zero-use agents removed, terse agent added, switched to phi4-mini (3.8B GPU).",
    steps: ["Real usage audit (39 entries)", "Killed 3 zero-use agents (documents, personal_projects, research)", "Added terse agent for command lookups", "Switched to phi4-mini (3.8B, GPU)", "Memory embedding 404 fixed", "Progress tracker filter (15→11 lessons)"],
  },
  {
    id: 11, version: "v0.4.1", date: "Apr 15, 2026",
    label: "Phase 11", title: "Signal-First Routing", color: "#C2410C", status: "done",
    summary: "QuerySignal normalizer replaces action-verb routing. Accuracy 70% → 92%; terse routing 0% → 100%.",
    steps: ["QuerySignal normalizer (domain, shape, verbosity)", "Reflection bias guard vs knowledge_learning", "Verbosity threshold ≤6 tokens (not ≤8)", "Routing accuracy: 70% → 92%", "Terse routing: 0% → 100%", "100-prompt eval suite"],
  },
  {
    id: 12, version: "v0.4.2", date: "Apr 20, 2026",
    label: "Phase 12", title: "FAISS Vector Backend", color: "#1E5A8A", status: "done",
    summary: "Replaced brute-force cosine search with FAISS IndexIDMap(IndexFlatIP): 592 vectors, 0.01 s cold rebuild.",
    steps: ["FAISSBackend class: IndexIDMap(IndexFlatIP)", "592 vectors indexed at startup", "Cold rebuild time: 0.01s", "Semantic similarity replaces brute-force loop", "Memory export → FAISS rebuild pipeline"],
  },

  // ── v0.5  Memory Intelligence ─────────────────────────────────
  {
    id: 13, version: "v0.5.0", date: "Apr 24, 2026",
    label: "Phase 13", title: "LRU Embedding Cache", color: "#0F766E", status: "done",
    summary: "@functools.lru_cache(maxsize=512) on get_embedding(): warm queries drop from 52 ms to 0 ms — 52× speedup.",
    steps: ["LRU cache maxsize=512 on get_embedding()", "Warm-query latency: 52ms → ~0ms (52× speedup)", "Cache hit rate ~94% on repeated query patterns", "Query embedding cached per session lifetime", "Cache stats exposed in /memory/stats response"],
  },
  {
    id: 14, version: "v0.5.1", date: "Apr 28, 2026",
    label: "Phase 14", title: "Memory Dedup + Consolidation", color: "#7E3F8F", status: "done",
    summary: "Near-duplicate detection (cosine > 0.93) at save time; bulk consolidation removed 236/828 entries (28.5%).",
    steps: ["_is_near_duplicate(): cosine > 0.93 → skip save", "consolidate(): scans all pairs, removes near-duplicates", "828 → 592 unique memories (236 removed, 28.5% reduction)", "Dedup runs on every new memory save via FAISS", "_DT_CONF_THRESHOLD=0.52 gates dual-trajectory", "_record_use(): use_count==5 → log-odds quality +0.03"],
  },
  {
    id: 15, version: "v0.5.2", date: "May 3, 2026",
    label: "Phase 15", title: "Core Brain", color: "#BE185D", status: "done",
    summary: "core_brain.py reasoning layer above router: classifies intent, action type, complexity, reflection need.",
    steps: ["BrainDecision dataclass: intent, action, complexity, agent_strategy", "Action types: lookup|build|debug|explain|compare|research|plan|unknown", "Complexity: simple|compound|ambiguous", "Fast path: rule-based ACTION_PATTERNS + DOMAIN_SIGNALS (no LLM)", "LLM path: phi4-mini for ambiguous/no-domain only (_llm_clarify)", "Reflection gating: build/debug + code agent → full; others → none"],
  },
  {
    id: 16, version: "v0.5.3", date: "May 7, 2026",
    label: "Phase 16", title: "Memory Health API", color: "#15803D", status: "done",
    summary: "Tier 2: live memory stats, prune, at-risk endpoints. Memory Health panel added to Progress tab.",
    steps: ["memory_stats(): total, by_type, by_agent, prune_candidates, never_used", "prune(): removes rows where quality < 0.55 AND use_count == 0", "GET /memory/stats — health snapshot", "POST /memory/prune — execute prune", "GET /memory/at-risk — quality 0.55–0.70, used ≤ 1×", "Memory Health panel in ProgressTab UI", "seed type weight: auto_train memories rank lower"],
  },
  {
    id: 17, version: "v0.5.4", date: "May 12, 2026",
    label: "Phase 17", title: "Dual-Trajectory Eval", color: "#9A6C00", status: "done",
    summary: "GRAM-light for python_dev + dotnet_dev on code/debug: Candidate A vs B scored by critic LLM.",
    steps: ["Applies to python_dev + dotnet_dev on code/debug tasks only", "is_code_task(): answer_shape must be 'code' or 'debug'", "Candidate A: full agent call", "Candidate B: lightweight LLM with chain-of-thought", "Critic: single LLM call picks A or B", "dual_trajectory_invoke() accepts force: bool param", "Confidence gate: skip if agent avg_conf > DT_CONF_THRESHOLD"],
  },
  {
    id: 18, version: "v0.5.5", date: "May 16, 2026",
    label: "Phase 18", title: "Ablation Eval — 99% Signal-Only", color: "#C2410C", status: "done",
    summary: "ablation_eval.py proves pure QuerySignal routing (99%) outperforms the full pipeline (97%). LLM fallback disabled on hot path.",
    steps: ["ablation_eval.py: 200-prompt suite, signal-only mode", "Pure QuerySignal: 99/100 (99%)", "Full pipeline (+ LLM): 97% — slower with no accuracy gain", "LLM fallback disabled by default on hot path", "AGENTIC_USE_SIGNAL=0 env var re-enables LLM mode", "Routing priority: factual→terse, verbosity≤terse→terse, domain_conf>0.3→domain, fallback→knowledge_learning"],
  },

  // ── v0.6  Reflection System ───────────────────────────────────
  {
    id: 19, version: "v0.6.0", date: "May 20, 2026",
    label: "Phase 19", title: "Reflection Triage", color: "#1E5A8A", status: "done",
    summary: "Structured triage collapses full-reflection rate from 58% to ~15% with full/light/none levels.",
    steps: ["_reflect_level(action, agent, confidence, complexity) returns (level, type_str)", "BrainDecision gains reflect_level: str field", "AgentState gains reflect_level: str field", "light mode: grounded_evaluate() only — no LLM critique", "Triage rules: explain/compare/plan/lookup → none; build+code+conf≥0.55 → light; build+code+conf<0.55 → full; debug+code → full; compound → full; conf<0.40 → full", "Full-reflection rate: 58% → ~15–20%"],
  },
  {
    id: 20, version: "v0.6.1", date: "May 24, 2026",
    label: "Phase 20", title: "User Feedback System", color: "#15803D", status: "done",
    summary: "Inline 👍/👎 feedback in Chat tab; ratings stored in feedback.db; fires apply_learning_update kernel.",
    steps: ["logs/feedback.db: feedback(id, timestamp, query, response, agent, rating, note)", "POST /feedback: stores rating + fires apply_learning_update(0.90 or 0.25)", "feedbackMap state tracks per-message ratings in ChatTab", "sendFeedback(msgIdx, rating) POSTs on click", "👍/👎 buttons rendered next to copy button", "Feedback uses same learning kernel as reflection signals"],
  },
  {
    id: 21, version: "v0.6.2", date: "May 27, 2026",
    label: "Phase 21", title: "Episodic Memory", color: "#0F766E", status: "done",
    summary: "Episodic memory type introduced: session-scoped, recency-weighted, 72-hour decay half-life.",
    steps: ["memory_type=episodic in schema", "Session ID tracked per conversation context", "Recency weight boosts recent episodic hits in retrieval", "Episodic decay: quality half-life ≈ 72h without recall", "Episodic count visible in Memory Health by-type breakdown", "High-recency episodic memories skip prune gate"],
  },
  {
    id: 22, version: "v0.6.3", date: "May 30, 2026",
    label: "Phase 22", title: "Failure Miner", color: "#B42318", status: "done",
    summary: "failure_miner.py scans trace logs for recurring failure patterns and saves them as priority memories.",
    steps: ["failure_miner.py: regex + embedding scan on logs/trace_dataset.jsonl", "Runs nightly; de-duplicates against existing failure memories", "Failure memories tagged type=failure in schema", "Priority injection: failure memories get top-k boost in retrieval", "Top 10 failures surfaced in Cognitive OS tab", "Failure rate tracked per agent in /metrics"],
  },
  {
    id: 23, version: "v0.6.4", date: "Jun 2, 2026",
    label: "Phase 23", title: "Contradiction Detection", color: "#C2410C", status: "done",
    summary: "Contradiction detector compares new memories against existing ones using cosine similarity + negation heuristic.",
    steps: ["contradictions.db schema: (id, memory_a, memory_b, conflict_score, timestamp)", "Conflict detection: cosine similarity + negation keyword heuristic", "Conflict score > 0.78 → logged as contradiction", "1 contradiction currently stored (unresolved)", "Triggered on every new memory save", "Resolution UI planned in Roadmap Phase 32"],
  },
  {
    id: 24, version: "v0.6.5", date: "Jun 4, 2026",
    label: "Phase 24", title: "Outcome-Weighted Memory", color: "#7E3F8F", status: "done",
    summary: "Memory quality retroactively updated from downstream task completion outcomes.",
    steps: ["Outcome signal propagated from task completion events", "Quality delta: ±0.05 per confirmed positive/negative outcome", "Memory weighting shifts toward task-proven memories over time", "outcomes.db stores outcome log per memory_id", "30-day quality trend available in /memory/stats", "Interacts with failure_miner: negative outcomes boost failure tagging"],
  },

  // ── v0.7  Refinement & UI ─────────────────────────────────────
  {
    id: 25, version: "v0.7.0", date: "Jun 5, 2026",
    label: "Phase 25", title: "React UI Decomposition", color: "#C48808", status: "done",
    summary: "Mission Control refactored into 18 isolated JSX components; forcedAgent lifted to App.js; CORS fixed.",
    steps: ["18 components split into dedicated .jsx files", "forcedAgent state owned by App.js (lifted from ChatTab)", "CORS: origins=['http://localhost:3000'] in FastAPI api.py", "Tab inventory normalized to NAV manifest in App.js", "Sidebar collapse state persisted to localStorage", "InspectContext wired from RunsTab → ContextInspectorTab"],
  },
  {
    id: 26, version: "v0.7.1", date: "Jun 6, 2026",
    label: "Phase 26", title: "Navigation Refactor + MenuBar", color: "#0F766E", status: "done",
    summary: "VS Code-style top MenuBar added; sidebar reduced to 5 pinned primary views; nav collision eliminated.",
    steps: ["MenuBar.jsx: Go / Debug / Analysis / Tools / View / Help menus", "Sidebar: 5 pinned items (Dashboard, Chat, Runs, Inspector, Cognitive OS)", "Go menu: all 5 sidebar-pinned items with ⊳ indicator", "Debug/Analysis/Tools menus: exclusive non-sidebar items only", "Modal system: About Agentic AI + Keyboard Shortcuts", "View menu: Toggle Sidebar + Clear Session Log"],
  },

  // ── v0.7  Refinement & UI (continued) ────────────────────────
  {
    id: 27, version: "v0.7.2", date: "Jun 7, 2026",
    label: "Phase 27", title: "Code Quality Cleanup", color: "#15803D", status: "done",
    summary: "20 inline sqlite3 imports consolidated; stale HOW TO APPLY block removed; phantom agents and config mismatch fixed.",
    steps: [
      "OLLAMA_MODEL=llama3 → phi4-mini in config/settings.env (config matched reality)",
      "20 inline 'import sqlite3 as _sq*' replaced by single top-level import in api.py",
      "3 inline sqlite3 imports removed from coordinator.py",
      "Stale 'HOW TO APPLY' comment block (18 lines) removed from api.py",
      "Phantom agents (documents, personal_projects, research) removed from /agents endpoint",
      "Stale next_phases roadmap array removed from /status endpoint",
    ],
  },
  {
    id: 28, version: "v0.7.3", date: "Jun 7, 2026",
    label: "Phase 28", title: "Keyboard Shortcuts + Settings UI", color: "#7E3F8F", status: "done",
    summary: "Global keyboard shortcuts wired; Settings modal with live API data; menu hints and reorganisation.",
    steps: [
      "Global keydown handler: Ctrl+1–5 (pinned tabs), Ctrl+K (focus chat), Ctrl+B (sidebar), Ctrl+, (settings), Ctrl+/ (shortcuts), Escape (close modal)",
      "Settings modal: reads /status + /memory/stats live — shows model, GPU, API URL, memory stats, coherence",
      "Shortcuts modal: replaced mouse-click instructions with grouped key bindings (Navigation / Interface / Chat)",
      "MenuBar: Ctrl hint annotations shown right-aligned on all shortcuttable items",
      "Mind Map moved from Tools → Analysis (correct grouping)",
      "Settings added to View menu with Ctrl+, hint",
    ],
  },
  {
    id: 29, version: "v0.7.4", date: "Jun 7, 2026",
    label: "Phase 29", title: "Action Pattern Coverage", color: "#C2410C", status: "done",
    summary: "ACTION_PATTERNS extended to eliminate ~10% action=unknown rate; 16 previously-unclassified query forms now resolve correctly.",
    steps: [
      "lookup: added 'show me', 'list all', 'list the' patterns",
      "build: added 'update', 'modify', 'change', 'refactor', 'optimize', 'improve', 'enhance', 'extend', 'add to'",
      "debug: added 'troubleshoot', 'diagnose', 'why is/does/won't/isn't/can't' patterns",
      "explain: added 'why does', 'why is', 'why would', 'what does', 'meaning of', 'help me understand'",
      "plan: added 'how to', 'help me', 'walk me through', 'best practice', 'recommend', 'how do I'",
      "Verified: 16 previously-unknown queries now correctly classified; 0 still return unknown",
    ],
  },
  {
    id: 30, version: "v0.8.0", date: "Jun 7, 2026",
    label: "Phase 30", title: "Docs/UI Architecture Alignment", color: "#0F766E", status: "done",
    summary: "AGENTS source-of-truth consolidated to constants.js; GET /docs API added; MindMap, GoalTracker, TaskQueue all import from constants.",
    steps: [
      "Removed local AGENTS arrays from MindMapInteractive, GoalTracker, TaskQueue",
      "All 3 components now import from constants.js — single source of truth",
      "Added GET /docs and GET /docs/{name} endpoints to api.py",
      "Docs serve markdown files from docs/ directory via allowlist",
      "known-issues.md and tracker-v3.md updated to match current state",
    ],
  },
  {
    id: 31, version: "v0.8.1", date: "Jun 7, 2026",
    label: "Phase 31", title: "Feedback Loop UI Activation", color: "#15803D", status: "done",
    summary: "Feedback analytics panel added to Progress tab with per-agent 👍/👎 distribution; learning update already wired through apply_learning_update.",
    steps: [
      "Feedback analytics panel added to Progress tab — shows total, per-agent bar chart, empty CTA",
      "Confirmed: 👍/👎 buttons in Chat tab POST to /feedback correctly",
      "Learning update: performance=0.90 (thumbs up) / 0.25 (down) flows through apply_learning_update",
      "Session log alert: first feedback triggers [feedback] print in server log",
      "Phase 31 marked done — pending: accumulating real ratings (0 collected so far)",
    ],
  },

  // ── v0.8  Loop Activation (continued) ────────────────────────
  {
    id: 32, version: "v0.8.2", date: "Jun 7, 2026",
    label: "Phase 32", title: "UI Polish + Revenue Strategy", color: "#C48808", status: "done",
    summary: "Menu hover bug fixed, sidebar upgraded (bold/larger, Introduction removed, separator gone), layout consistency pass across all 16 content tabs, open-core revenue roadmap established.",
    steps: [
      "MenuBar.jsx — hover !important CSS bug fixed: hoveredTop React state replaces CSS rule, open state always wins (F-18)",
      "Sidebar — Introduction removed from SIDEBAR_PINNED, separator removed, font 12/400 → 13/600, active 600 → 700, symbol 13 → 14px",
      "Layout consistency — maxWidth + margin: 0 auto removed from 16 tab roots; App.js is sole layout authority (F-19)",
      "HomeTab scroll wrapper removed — parent App.js handles scroll; padding unified to 24px 28px",
      "ResearchTab and ChatTab retain own layout management (full-height document reader / chat)",
      "docs/ROADMAP-REVENUE.md created — 5-phase commercial roadmap with exit criteria",
      "Business model decided: open core — MIT source + paid managed hosting/enterprise features",
      "Open-source strategy: privacy claim requires verifiable code; GitHub stars replace ad budget",
    ],
  },
  {
    id: 33, version: "v0.8.3", date: "Jun 8, 2026",
    label: "Phase 33", title: "Contradiction Resolution", color: "#E05252", status: "done",
    summary: "Auto-resolve conflicting memories (prefer newer), two new API endpoints, Contradictions panel on Cognitive OS tab with expandable diff view and one-click resolution.",
    steps: [
      "memory_db.auto_resolve_conflicts(threshold, dry_run) — keep newer memory (higher id) over higher-quality when cos ≥ threshold",
      "GET /memory/auto-resolve — dry-run preview of conflicting pairs",
      "POST /memory/auto-resolve — execute resolution + FAISS rebuild",
      "ContradictionsPanel in CognitiveOSTab.jsx — list + expandable diff view (query + response excerpt)",
      "Auto-Resolve button calls POST /memory/auto-resolve?threshold=0.90, shows inline result banner",
    ],
  },
  {
    id: 34, version: "v0.8.4", date: "Jun 8, 2026",
    label: "Phase 34", title: "Prompt Quality IDE", color: "#1E5A8A", status: "done",
    summary: "Prompt Editor reborn as a Prompt Quality IDE: 5 collapsible analysis sections, domain-aware missing context detection, AI execution forecast, agent recommendation, and one-click heuristic auto-repair with before/after diff view.",
    steps: [
      "Prompt Health — 5 metrics (Clarity, Structure, Specificity, Actionability, Token) with overall score",
      "Execution Forecast — Accuracy, Reasoning Depth, Consistency, Hallucination Risk derived from prompt signals",
      "Missing Context — domain-aware gaps (6 domains: Software, ML, Python, Networking, Writing, Business)",
      "Suggested Agents — domain confidence + ranked specialist recommendations from local agent registry",
      "Prompt Upgrade — heuristic Auto Fix with v1→v2 score trajectory and Apply button",
      "Domain detection engine (JS) — keyword matching across 6 domain profiles with confidence scoring",
    ],
  },
  {
    id: 35, version: "v0.8.5", date: "Jun 8, 2026",
    label: "Phase 35", title: "FAISS Backend Swap", color: "#0F766E", status: "done",
    summary: "FAISSBackend formally activated with auto-promote hook, enhanced monitoring, latency benchmark, and expanded DataTab panel. Vector search P50: 0.38ms at 628 entries.",
    steps: [
      "promote_if_needed() — auto-promotes SQLite→FAISS when count ≥ 800; called at startup and available via POST endpoint",
      "benchmark_retrieval() — times vector search (C++ layer) and full pipeline (embed+search+rerank) separately",
      "GET /analysis/memory_backend — extended: index_ntotal, drift_pct, index_size_mb, promote_threshold",
      "GET /analysis/memory_backend/bench — P50/P95 for vector-only vs full pipeline",
      "POST /analysis/memory_backend/promote — manual one-click promote from UI",
      "DataTab MemoryBackendPanel — stat cards for index vectors, drift %, index file size, latency; Benchmark button; SQLite promote bar",
    ],
  },
  {
    id: 39, version: "v0.9.3", date: "Jun 12, 2026",
    label: "Phase 39", title: "Threading + Eval Integrity", color: "#9A6C00", status: "done",
    summary: "The #1 user-visible gap: stateless /ask replaced with real conversation threading. F10 SQLite consolidation finally ships. Production routing telemetry begins collecting the real-world eval dataset the benchmark needs.",
    steps: [
      "F10: Consolidate 8 SQLite databases → single amagra.db with versioned schema migrations",
      "threads + turns tables — session_id on /ask, rolling context window (last 4-6 turns) within phi4-mini context limit",
      "ChatTab thread rail — per-thread message history, thread selector sidebar, new thread button",
      "Routing telemetry: log every query → agent assignment + was_correct signal to telemetry.db",
      "GET /telemetry/routing — query distribution, per-agent hit rate, flagged misroutes for human review",
      "Eval integrity split: curated-eval (current 138 queries) vs telemetry-eval (real production queries) tracked separately",
      "README pitch rewrite: outcomes-first (latency reduction, not routing architecture), benchmark caveat documented",
      "Landing CTA hardened: /register/free endpoint wired to actual provisioning (SendGrid onboarding email active)",
    ],
  },
  {
    id: 38, version: "v0.9.2", date: "Jun 11, 2026",
    label: "Phase 38", title: "Stability + Observability UI", color: "#0F766E", status: "done",
    summary: "h_UCI 75.1 → 80.8: productivity metric fix (runs.db), critic gate recalibrated (AST syntax check), confidence divisor tightened. 21 skill nodes with phrase-weighting. Team tier org_id end-to-end. Self-service /register/free, /pricing, rate-limit headers. UCIDashboard health strip + delta badge. SkillsTab 21-node browser. Menu deduplication (8 clean menus, no duplicate routes, all tabs reachable). Brand unified to Amagra.",
    steps: [
      "metrics_engine: _productivity_metrics() reads runs.db pass/fail — Productivity 42.5 → 80.6, h_UCI → 80.8",
      "reflection.py: critic gate uses ast.parse() syntax check instead of subprocess execution — false-positive rate eliminated",
      "decision_weights: to_confidence() divisor 1.5 → 1.35, calibration factor 0.20 → 0.15 — default confidence 0.67 → 0.74",
      "skill_graph: 18 → 21 nodes (DataAnalysis, TechnicalWriting, QuickLookup) with phrase-weighted scoring",
      "planner: world-model context injected into first plan step and LLM prompt",
      "api_keys + admin + cos: org_id threaded end-to-end for team shared world model session",
      "routes/register.py: POST /register/free (100 req/day, max 3/email) + GET /pricing (4 plan tiers)",
      "api.py auth middleware: X-RateLimit-Limit/Used/Remaining headers on all auth responses",
      "routes/core.py /health: Ollama connectivity, memory backend type+count, live UCI",
      "UCIDashboard: HealthStrip (Ollama/Memory/API dots) + h_UCI delta badge vs baseline 75.1",
      "SkillsTab.jsx: 21-node skill browser with agent/category filters and search",
      "MenuBar: 8 clean menus (Go/Debug/Observe/Explore/Tools/Docs/View/Help) — 8 tabs previously unreachable, 4 duplicate routes removed",
      "Ctrl+5 → UCI Dashboard (was Cognitive OS), Ctrl+Shift+R → Decision Replay, Ctrl+Shift+M → Memory Browser",
      "Brand unified: Agentic AI → Amagra throughout UI and API title",
    ],
  },
  {
    id: 37, version: "v0.9.1", date: "Jun 10, 2026",
    label: "Phase 37", title: "Cognitive IDE + Monetization", color: "#C2410C", status: "done",
    summary: "Monetization path (Stripe, SendGrid, idempotency), auth hardening, and five new observability tabs: Plan Graph SVG DAG, Memory Browser with FAISS visibility, Decision Replay with side-by-side diff. Plan step status tracking and 18-node skill graph.",
    steps: [
      "payments.py — Stripe Checkout ($39/mo Developer), webhook handler, idempotency via processed_events table (INSERT OR IGNORE)",
      "email.py — SendGrid HTML + plain-text transactional email for API key delivery",
      "Auth hardening — REQUIRE_AUTH env flag, ENV=production guard (RuntimeError if auth off in prod), .env.example",
      "PlanGraphTab.jsx — pure SVG DAG, parallel level columns, node status/uncertainty/elapsed_ms, click-to-detail panel",
      "MemoryBrowserTab.jsx — 500-record browser, FAISS backend badge, type/agent/sort filters, quality bars",
      "DecisionReplayTab.jsx — session history list, re-run via POST /ask/replay, side-by-side compare panel",
      "deep_pipeline.py + planner.py — PlanStep.status tracked live (running/completed/failed), elapsed_ms captured",
      "GET /plan/graph, POST /ask/replay, GET /verify/stats, GET /verify/recent — 4 new endpoints",
      "skill_graph.py — 16→18 nodes: added TestingQA (python_dev) and CloudInfrastructure (it_networking)",
    ],
  },
  {
    id: 36, version: "v0.9.0", date: "Jun 8, 2026",
    label: "Phase 36", title: "Open Source Launch + Auth Foundation", color: "#C48808", status: "done",
    summary: "API key auth layer (X-API-Key, SHA-256 hashes, tiers, daily limits), memory namespace isolation, Docker Compose stack, and README for public launch.",
    steps: [
      "api_keys.py — create_key, verify_key, increment_usage, get_usage, TIER_LIMITS (free/developer/team/enterprise)",
      "Auth middleware in api.py — REQUIRE_AUTH env flag, 401/403/429 responses, key record injection",
      "Memory namespace isolation — owner_key_id column migration in memories table at startup",
      "GET /usage — per-key daily usage stats with remaining quota",
      "POST /admin/keys — create key (raw shown once), GET list, DELETE deactivate",
      "Dockerfile + docker-compose.yml — API + Ollama (GPU passthrough) + UI services with persistent volumes",
      "README.md — quick start, architecture diagram, auth guide, tier table, managed hosting CTA",
    ],
  },

  // ── v0.9 Transformation Audit — Phases 1–4 ───────────────────────────────────
  {
    id: 50, version: "v0.9.4", date: "Jun 11, 2026",
    label: "Audit Phase 1", title: "Security Hardening", color: "#B42318", status: "done",
    summary: "All critical and high-severity issues resolved before internet exposure. Auth deny-by-default, CORS lockdown, per-minute rate limiting, CI/CD pipeline, streaming shipped to UI.",
    steps: [
      "Auth deny-by-default — _PUBLIC_PATHS allowlist; all ~40 routes gated when REQUIRE_AUTH=1",
      "Admin proxy hole fixed — removed host==127.0.0.1 bypass; ADMIN_TOKEN required or 503",
      "CORS locked down — ALLOWED_ORIGINS env var; no wildcard",
      "Per-minute rate limiting — sliding window: free 10/min · dev 60/min · team 300/min",
      "X-RateLimit-Limit/Used/Remaining headers on all authenticated responses",
      "GitHub Actions CI — ruff lint + pytest + Docker build on every push/PR",
      "README drift fixed — 'No streaming' claim removed; /ask/stream documented",
      "ChatTab wired to POST /ask/stream — tokens render as they arrive with cursor",
    ],
  },
  {
    id: 51, version: "v0.9.5", date: "Jun 12, 2026",
    label: "Audit Phase 2", title: "Async, Concurrency & UI Consolidation", color: "#C48808", status: "done",
    summary: "Async /ask frees event loop during LLM calls. WAL mode on all 17 SQLite DBs. Tenant isolation via ContextVar. 29-tab cockpit collapsed to 4 clean surfaces.",
    steps: [
      "Async /ask — coordinator.invoke wrapped in run_in_executor; event loop no longer blocks",
      "WAL mode — PRAGMA journal_mode=WAL on all 17 SQLite DBs at startup; eliminates 'database is locked'",
      "Tenant scoping — ContextVar[int] propagates owner_key_id; search() filters per-tenant; save() stamps new rows",
      "UI consolidation — 29 tabs → 4 surfaces: Chat · Memory · Inspect · Settings",
      "SubNav horizontal strip component — tracks last active sub-tab per surface",
      "SSE stream enriched — routing + done events carry full BrainDecision metadata",
    ],
  },
  {
    id: 52, version: "v0.9.6", date: "Jun 12, 2026",
    label: "Audit Phase 3", title: "Memory Surface, Multi-provider & Brand", color: "#0F766E", status: "done",
    summary: "Memory surfaced inline in responses. All emoji replaced with clean unicode symbols. Multi-provider /ask wires Anthropic directly with brain-based routing.",
    steps: [
      "Memory callouts — '◈ Remembered · [snippet]' auto-show top 2 below responses; 'show N more' toggle",
      "Emoji → unicode — AGENTS, PROGRESS_STEPS, PROMISES, STARTER_PROMPTS: ◈ λ ⊹ ∑ ¶ ∴ ⊃ § ⊓ ⬡ ⚙ ▸",
      "Action buttons cleaned — 📋→⊞ · 🗑→× · 📌→◆ · 👑 Auto→◈ Auto",
      "Multi-provider /ask — provider: 'anthropic' field on AskRequest; think() selects agent+system prompt",
      "AnthropicProvider.generate() called directly; Ollama coordinator is fallback",
      "PREFER_ANTHROPIC=1 env var for automatic provider selection",
      "model_used field added to AskResponse",
    ],
  },
  {
    id: 53, version: "v0.9.7", date: "Jun 12, 2026",
    label: "Audit Phase 4", title: "Luxury UI & Brand Identity", color: "#B45309", status: "done",
    summary: "VS Code clone identity replaced. Shared design token system. Routing animation turns the differentiator visible. Feedback loop closed with inline acknowledgment.",
    steps: [
      "Brand color — #C48808 (VS Code Blue) replaced with #C48808 (sky blue) across theme.js + index.css + App.js",
      "Shared tokens — theme.js exports T, FONT_UI, FONT_MONO, SPACE, RADIUS; App.js + ChatTab import it",
      "Canvas deepened — body #F4F0E8→#F0E9DF; surface #FAF7F2→#FAF7F2; text #2E2010→#2E2010",
      "Routing animation — RoutingStrip shows '◈ analyzing…'→'◈ [domain]→[agent]' while awaiting tokens",
      "routeFadeIn + routePulse CSS keyframes; strip collapses when first token arrives",
      "Feedback acknowledgment — '◈ Got it — routing adjusted' / '◈ Got it — I'll improve' fades out 3.5s",
      "Typography — JetBrains Mono top of monospace stack in theme.js + index.css",
    ],
  },

  // ── v0.10  Content & Launch ───────────────────────────────────────────────────
  {
    id: 60, version: "v0.10.1", date: "Jun 12, 2026",
    label: "Phase 1 of v0.10", title: "RAG File Context", color: "#C48808", status: "done",
    summary: "Users attach files in chat. Chunks embedded into the FAISS memory layer. Top-k relevant chunks injected into every LLM call that references the files.",
    steps: [
      "POST /documents/upload — extract text, chunk with RecursiveCharacterTextSplitter (800c/100 overlap), embed into FAISS",
      "GET /documents — list stored files with chunk counts",
      "DELETE /documents/{filename} — delete all chunks; re-upload is idempotent",
      "AskRequest gains context_files: list[str] field",
      "_get_document_context() — cosine search over document mem_type, injects into task message",
      "Both /ask and /ask/stream inject document context before the LLM call",
      "ChatTab: ⊕ attach button, chip row with uploading/ready/error states, × to remove",
      "Supported: .txt .md .py .js .ts .jsx .tsx .json .yaml .html .css .sh .sql .csv .pdf .toml .rst",
    ],
  },

  // ── v1.0  First Public Release ────────────────────────────────────────────────
  {
    id: 70, version: "v1.0.0", date: "Jun 13, 2026",
    label: "First Public Release", title: "Amagra 1.0", color: "#15803D", status: "done",
    summary: "The public debut. Signal-first routing, 10 domain agents, persistent FAISS memory, the Cognitive OS observability layer, RAG file context, auth + rate limiting, and the Gilded Calm UI — everything from the v0.1 → v0.10 internal builds, released to the public for the first time.",
    steps: [
      "Signal-first routing — QuerySignal classifies most queries in ~1ms, escalates to CoreBrain only when ambiguous",
      "10 registry-canonical domain agents with per-agent memory + 21-node skill-graph disambiguation",
      "Persistent semantic memory: SQLite → FAISS auto-promote at 800 entries → 52× LRU cache (<1ms warm)",
      "Cognitive OS: event_bus, world_model, metrics_engine, cognitive_state — browsable in real time",
      "Auth deny-by-default (_PUBLIC_PATHS allowlist), CORS lock, sliding-window rate limits, X-RateLimit-* headers",
      "Docker Compose (Ollama GPU passthrough + API + UI), MIT licensed, fully self-hosted",
      "CI: ruff + pytest + Docker build on every push and PR",
    ],
  },
  {
    id: 71, version: "v1.0.1", date: "Jun 13, 2026",
    label: "Launch Polish", title: "Lean Runtime & Onboarding", color: "#0F766E", status: "done",
    summary: "Post-debut hardening. A neutral lean runtime core (Context/Result spine, onion middleware, lazy registry, append-only run log) now sits under the router behind a frozen delta-algebra dispatch reducer. First-run onboarding, the CRA → Vite migration, and a centralized SQLite path registry land the bulk of the deferred v1.0.1 engineering. Test suite grows 544 → 624.",
    steps: [
      "core/ lean runtime — neutral Context/Result spine, onion middleware, lazy registry, append-only run log",
      "Delta-algebra routing seam — frozen dispatch reducer, router score/decide split",
      "infrastructure/db.py — centralized SQLite path registry (consolidation seam toward a single amagra.db)",
      "First-run onboarding — Ollama + model-pull detection, guided first prompt",
      "UI migrated CRA → Vite (.js → .jsx); landing-style luxe-card system ported to the dashboard",
      "Test suite 544 → 624 passing (contract, dispatch reducer, runtime, run log, routing seam, providers, registry)",
      "Repo polish — README badge row + Star History chart, topics, homepage",
    ],
  },
  {
    id: 72, version: "v1.0.2", date: "Jun 14, 2026",
    label: "Dashboard & Community Polish", title: "Luxe Dashboard & Community Profile", color: "#0F766E", status: "done",
    summary: "The landing-style luxe-card system now spans the whole dashboard, and the repo gains a full community profile (Contributing, Code of Conduct, Security) plus a branded social-preview card.",
    steps: [
      "Luxe-card system extended across 10 tabs — Cognitive Map, Cognitive OS, Event Log, Home, Memory Browser, Plan Graph, Policy, Risk Observatory, Skills, Version History",
      "Rounded badges/pills + shared PageHeader/RefreshBtn from ObsShared across observability views",
      "Fix: CognitiveMapTab `T as C` alias left card/blue/green colors undefined — explicit local palette",
      "Community health files — CONTRIBUTING.md, CODE_OF_CONDUCT.md (Covenant 2.1), SECURITY.md",
      "Gilded Calm social-preview card (1280×640) for GitHub link sharing",
      "Vite build verified; community profile 85%",
    ],
  },
  {
    id: 73, version: "v1.0.3", date: "Jun 14, 2026",
    label: "Single-File DB", title: "Single-File DB Consolidation", color: "#0F766E", status: "done",
    summary: "Completes the AMAGRA_DB seam opened in v1.0.1 so the whole system can run from one SQLite file. A one-shot migration consolidates every separate store losslessly, and the start scripts + Docker now opt into single-file mode with one env var. Test suite grows 624 → 645.",
    steps: [
      "scripts/migrate_to_single_db.py — one-shot consolidation, preserves rowid for every table (FAISS IndexIDMap is keyed on memories.id) + the FAISS sidecar",
      "Migration is dry-run by default; --archive moves old files aside; refuses to clobber a same-named table with a different schema",
      "Registry completion — registrations + telemetry routed through infrastructure/db.py (were hardcoded, so single-file mode silently skipped them)",
      "api.py WAL setup derived from the registry (distinct_paths) — honours single-file mode, no drift",
      "Cutover wiring — start-agents.sh + docker-compose.yml pass AMAGRA_DB through (./data volume); README documents the migrate → flip flow",
      "Memory portability — lossless JSON export/import (base64 embeddings, no model call on re-import) + Markdown export; GET /memory/export.json|.md, POST /memory/import",
      "Test suite 624 → 645 passing",
    ],
  },
  {
    id: 74, version: "v1.0.4", date: "Jun 14, 2026",
    label: "Tool-Using Foundations", title: "Tool-Using Foundations", color: "#0F766E", status: "done",
    summary: "The first wave of v1.1 tool-using capabilities, delivered on the v1.0.x line: thread management, a jailed file tool, sandboxed code execution, and chat stop/regenerate/edit. Live web search + the in-agent tool loop remain for v1.1.0. Test suite grows 645 → 690.",
    steps: [
      "Thread management — PATCH /threads/{id} (rename), POST .../fork, .../archive, .../truncate; GET /threads gained include_archived",
      "Jailed file tool — tools/workspace.py read/list/search confined to $AMAGRA_WORKSPACE via (root/p).resolve().is_relative_to(root); GET /workspace/*",
      "Sandboxed code execution — tools/sandbox.py python3 -I -S under setrlimit + scrubbed env + process-group timeout; POST /sandbox/run, opt-in via AMAGRA_SANDBOX (network not isolated)",
      "Chat affordances — stop, regenerate, edit-and-resend in the composer, backed by thread truncation",
      "Fix: temporal-dead-zone ReferenceError that blanked the dashboard; added a top-level ErrorBoundary",
      "Test suite 645 → 690 passing",
    ],
  },
  {
    id: 75, version: "v1.1.0", date: "Jun 15, 2026",
    label: "Tool-Using Agents", title: "Tool-Using Agents", color: "#15803D", status: "done",
    summary: "Completes the v1.1 tool-using milestone: live web search and a provider-agnostic in-agent tool loop, plus a beginner-friendly UI (Simple/Advanced mode + reworked onboarding) and a routing over-classification guard. Test suite grows 690 → 719; 132 routes.",
    steps: [
      "Live web search — tools/web.py provider abstraction (default SearXNG, opt-in Brave/Tavily); GET /search/web + /search/status, uniform {title,url,snippet}",
      "In-agent tool loop — tools/tool_loop.py provider-agnostic loop (model emits fenced JSON {tool,args} → execute → observe, bounded rounds) + tools/catalog.py; GET /tools/list, POST /tools/run",
      "Simple/Advanced UI mode — Simple trims chrome to Chat/Library/Guide and hides technical menus + diagnostics; persists in localStorage, toggleable from menu bar, Settings, and onboarding",
      "Onboarding reworked — plain-language, privacy-first copy instead of Ollama/model jargon",
      "Routing guard — build over-classification guard, profile-leak framing fix, embedding warm-up",
      "Test suite 690 → 719 passing · 132 routes",
    ],
  },
  {
    id: 76, version: "v1.1.1", date: "Jun 15, 2026",
    label: "Tools in the Default Path", title: "Tools in the Default Path", color: "#15803D", status: "done",
    summary: "Wires the in-agent tool loop into the default specialist path (config-gated, off by default) and clears a wave of retrieval, routing, and multilingual fixes from the issue queue. Test suite grows 719 → 766.",
    steps: [
      "Tool loop in the default agent path — tools/agent_runtime.py respond_with_optional_tools() across all 10 agents, gated behind AMAGRA_AGENT_TOOLS=1, falls back to plain invoke (#8, #5)",
      "Domain-affinity retrieval penalty — off-domain memories down-weighted via prefer_agent; unified rank_select() across SQLite/FAISS/pgvector, also repairing the episodic cap on FAISS (#14, #13)",
      "Learned-router auto-retrain — orchestration/auto_retrain.py retrains every LEARNED_ROUTER_RETRAIN_EVERY real sessions (default 50), single-flight in the background (#15)",
      "Multilingual profile-leak fix — core/language.py flags non-English input, drops the profile block, and steers reply language (#6)",
      "Routing & detection — min-keyword threshold for short queries (#10) + compound-detection benchmark, FP-rate 0.00 (#11)",
      "Test suite 719 → 766 passing",
    ],
  },
  {
    id: 77, version: "v1.1.2", date: "Jun 16, 2026",
    label: "Eval Rigor & Security Hardening", title: "Eval Rigor & Security Hardening", color: "#15803D", status: "done",
    summary: "An honesty-and-hardening release: collapses the redundant keyword router, closes routing-eval label leakage, ships a sealed adversarial routing set with confidence intervals, and lands the §3 security review fixes. Test suite grows 766 → 790.",
    steps: [
      "Router collapse — removed the discarded keyword router from the coordinator hot path; core_brain is the sole routing authority (#20)",
      "Label-leakage guard — learned-router training drops fuzzy-joined and thumbs-down traces (trustworthy_only); DOMAIN_TO_AGENT KeyError guard (#19, #20)",
      "Sealed adversarial routing set — held-out paraphrase + cross-domain prompts with Wilson CIs, plus a Fleiss' κ multi-rater agreement harness; honest accuracy floor documented in FINDINGS.md",
      "Security (§3 review) — constant-time admin-token compare, RLIMIT_NPROC fork-bomb guard, exposure docs, and a fail-closed prod-boot regression test (S1/S4/S5, PR #24)",
      "Test suite 766 → 790 passing",
    ],
  },
  {
    id: 78, version: "v1.2.0", date: "Jun 17, 2026",
    label: "Model Choice & Desktop Mode", title: "Model Choice & Desktop Mode", color: "#15803D", status: "done",
    summary: "Switch provider/model at runtime from the UI — no env edits, no restart — and run the whole app as a single process that serves its own dashboard. Ships an AppImage build path.",
    steps: [
      "Settings → Model tab — runtime provider/model swap via infrastructure/provider_config.py + routes/settings_provider.py; live reload hits the agent hot path immediately",
      "Single-process desktop mode — api.py serves the built UI from ui/build at / (StaticFiles), API routes win, UI assets bypass auth",
      "infrastructure/paths.py — AMAGRA_DATA_DIR / OS user-data dir resolution for db.py + provider_config.py",
      "AppImage packaging (packaging/) — relocatable-python + appimagetool",
      "Test suite → 808 passing",
    ],
  },
  {
    id: 79, version: "v1.3.0", date: "Jun 18, 2026",
    label: "Cross-Model Prompt Debugger", title: "Cross-Model Prompt Debugger", color: "#C48808", status: "done",
    summary: "The launch wedge: run one prompt across many models at once and read the outputs side by side. Reuses the provider/model settings from v1.2.0, so any configured model works unchanged. Published as a multi-arch Docker image.",
    steps: [
      "POST /debug/prompt — fans one prompt across N models concurrently with per-model error isolation (routes/debug_prompt.py)",
      "Run Across Models panel — target checkboxes + stacked result cards in ui/src/PromptEditorTab.jsx",
      "Cloud SDKs (anthropic, openai) bundled — compare Claude / GPT / local; local works offline with no key",
      "Multi-arch Docker Hub publish on every v* tag (.github/workflows/publish.yml)",
    ],
  },
  {
    id: 80, version: "v1.3.1", date: "Jun 20, 2026",
    label: "Debugger Divergence Highlight", title: "Debugger Divergence Highlight", color: "#C48808", status: "done",
    summary: "Completes the debugger: when two or more models answer, a summary shows how much they actually agree — the whole point of comparing side by side.",
    steps: [
      "Client-side divergence summary in Run Across Models — average pairwise Jaccard overlap of output word sets",
      "Verdict (Aligned / Mixed / Divergent) + agreement %, agreement bar, and word-count spread",
      "Reconciled stale version state — landing badge, BUILD_PHASES history (v1.2.0, v1.3.0), and lockstep version markers",
    ],
  },
  {
    id: 81, version: "v1.4.0", date: "Jun 20, 2026",
    label: "Unified Workspace UI", title: "Unified Workspace UI", color: "#7E3F8F", status: "done",
    summary: "Consolidates the dashboard into six coherent views — Workspace · Runs · Cognition · Memory · Research · Settings — driven by a single nav model, with system health promoted to a hero dashboard. A reorganization of what already exists: no components removed, no new backend.",
    steps: [
      "Single data-driven nav model (SURFACES) — sidebar, calm SubNav dropdown, surface lookup, and per-surface last-tab memory all derive from one source; each view carries a one-line description",
      "Six views replace the Chat/Library/Memory/Inspect/Settings split — Workspace (Chat · Prompt IDE · Goals · Tasks · Project State), Runs (Overview · Runs · Decisions · Trace · Inspector · Policy · Replay), Cognition, Memory (+ Library folded in), Research (Lab · Analysis), Settings",
      "Cognition dashboard — UCIDashboard · Risk · Events · Plan composed into one responsive grid (CognitionView.jsx), 'observability as hero'",
      "Refreshed keyboard map (Ctrl+1..7) + Go menu for the six surfaces",
      "Deferred to v1.4.1: run-scoped Runs master-detail (needs run-id plumbing in Traces/Inspector/Policy); Monaco code pane + write endpoint; theme.js token extraction",
    ],
  },
  {
    id: 82, version: "v1.4.1", date: "Jun 21, 2026",
    label: "UI Refinement", title: "UI Refinement — Minimal & Premium", color: "#7E3F8F", status: "done",
    summary: "A consistency and polish pass over the six-view workspace: removes the duplicate top menu bar, unifies page headers and stat cards, and de-clutters the Cognition hero dashboard for a calmer, more premium feel. No backend or behavior changes.",
    steps: [
      "Removed the redundant top MenuBar — its Go menu duplicated the sidebar and Debug/Observe/Explore/Tools just re-cut existing sub-tabs; rehomed the brand + global actions into the sidebar (footer cluster: Settings/Shortcuts/More + Simple-Advanced toggle), reclaiming 52px of vertical height",
      "Consistent serif PageHeader across every view — added headers to Tasks/Overview/Knowledge/Timeline/Guide and converted Trace/Analysis/Model from bold-sans titles",
      "Cognition hero dashboard de-cluttered — an `embedded` prop makes UCI/Risk/Events/Plan suppress their own headers so each cell shows a single uppercase title; content fills, taller cells",
      "Unified stat cards on the lux-card look (gloss + tabular value + uppercase tracked label) across Knowledge/Analysis/Overview to match Policy/Memory",
    ],
  },
  {
    id: 83, version: "v1.4.2", date: "Jun 21, 2026",
    label: "Gold Refinement", title: "Gold Refinement — Premium Polish", color: "#7E3F8F", status: "done",
    summary: "A luxury polish pass: gold-gradient page titles, the landing-page gold hover border applied consistently to every card, and a card sweep that promotes the remaining flat panels to the lux-card recipe. Charts keep their semantic colors for readability.",
    steps: [
      "PageHeader titles now use the AMAGRA/Memory gold gradient by default (gold opt-out retained)",
      "Every .lux-card gains the landing .feature-card hover treatment — a gradient gold border (g1→g3→g5) that fades in on hover, drawn as a masked ::after so it paints only the ring, never over content",
      "Card sweep — promoted standalone flat panels to lux-card across Tasks, Analysis, Goals, Decisions, Knowledge, and Mind Map; skipped inputs/chips/rows and stat-tile-grid wrappers to avoid card-on-card nesting",
      "Charts deliberately keep semantic colors (risk/quality/pass-fail) — gold stays on titles, hover borders, and decorative chrome",
    ],
  },
  {
    id: 84, version: "v1.4.3", date: "Jun 22, 2026",
    label: "Card & Layout Refinement", title: "Card & Layout Refinement", color: "#7E3F8F", status: "done",
    summary: "Review-driven polish of the gold pass: fixes card-in-card nesting on the Cognition dashboard, restores an elegant serif gold title with one consistent stacked header rule, tunes the hover to match the landing card, and aligns every tab to the same page layout.",
    steps: [
      "Cognition dashboard: a scoped rule flattens nested lux-cards so each cell is the ONLY card — no more card-in-card (or nested gold borders)",
      "Elegant serif (Cormorant Garamond) gold-gradient titles, and one consistent header rule everywhere — Title, then description, then actions/forms stacked on new lines below",
      "Hover matches the landing .feature-card — gradient gold border + soft gold glow together, rounder 16px corners",
      "Aligned Runs & Trace to the standard centered/padded page (were full-height shells) and normalized the last custom headers (Project State, Library, Releases, Progress, Promises) onto PageHeader",
    ],
  },
  {
    id: 85, version: "v1.4.4", date: "Jun 22, 2026",
    label: "Single Gold Favicon", title: "Single Gold Favicon", color: "#7E3F8F", status: "done",
    summary: "Collapse the icon set to one mark: a single gold AMAGRA wordmark SVG favicon. Every raster icon variant is removed and all references point at the one file.",
    steps: [
      "icon.svg is now the gold AMAGRA wordmark (serif, gold gradient, width-pinned so it renders without the web font)",
      "Removed favicon.ico, favicon-32.png, apple-touch-icon.png, logo192.png, logo512.png",
      "index.html, landing.html, and manifest.json reference only icon.svg",
    ],
  },
  {
    id: 86, version: "v1.4.5", date: "Jun 22, 2026",
    label: "Observability & Favicon Fix", title: "Component Transparency & Icon-Usable Favicon", color: "#7E3F8F", status: "done",
    summary: "Adds a transparent/opaque view of the running system on top of the event bus, fixes a latent event-key bug, and recomposes the v1.4.4 favicon so the AMAGRA wordmark is legible at icon size.",
    steps: [
      "Component Transparency: classify_components() + GET /cos/transparency + UCIDashboard panel — labels each component transparent | partial | opaque | unobserved from the evidence + confidence its events disclose (read-only over events.db, no new data collected)",
      "event_bus key fix: emit/subscribe now use EventType.value, not str(enum) — repairs documented wildcard subscriptions and two dead suggestion_engine heuristics; historical events.db migrated to the dotted form",
      "Verifier, Router, and Risk Gate now disclose evidence+confidence (transparency_score 0.0 → 0.23); routing (AGENT_SELECTED) is now emitted",
      "Favicon: gold AMAGRA wordmark recomposed onto a square 512 dark tile with gold ring (was a 720×220 wordmark that rendered ~5px tall and illegible in the tab)",
      "Known issues (tracked as GitHub issues): Responder & Dispatch still opaque; Intake stays partial (no routing confidence at query-receipt); 7 components read 'unobserved' until exercised by traffic; favicon is SVG-only (no raster/apple-touch fallback)",
    ],
  },
  {
    id: 87, version: "v1.4.6", date: "Jun 23, 2026",
    label: "OCAC Stability Metrics", title: "Contraction/Lyapunov Theory + Dashboard Observability", color: "#7E3F8F", status: "done",
    summary: "Frames the learning loop as a parametrised contraction fixed-point family (OCAC) and imports its proved consequences as live metrics — then surfaces those metrics on the dashboard so the stability signal is visible, not just computed.",
    steps: [
      "math_metrics.py: pure, self-tested OCAC-bridge functions (effective_contraction, resolvent_bound, affine_lyapunov_decay, instability_conjunctive, series_curvature, invariant_health, chain_error_bound, gevrey_majorant, stable_recursion_depth)",
      "learning.py: adaptive-α gate instability switched from a 0.4/0.4/0.2 weighted average to conjunctive soft-OR — a single failing OCAC signal now halts learning instead of being diluted",
      "coherence.py: C_quality decoupled from routing (independently-graded memory quality, restoring effective DOF) + Δ²C curvature channel & peak alarm",
      "metrics_engine.py: routing_accuracy source-tagged (measured from arena.db vs assumed_constant) + uci_history()/uci_curvature() expose the UCI trajectory and its Δ² leading indicator",
      "Dashboard: GET /cos/uci/trajectory; UCIDashboard UCI trajectory sparkline + Δ² bend-alarm badge + measured/assumed source badge; CognitiveOSTab Δ²C bend-alarm badge + sharpest-bend ring on the C(t) timeline",
      "Curvature is the leading indicator: it catches the acceleration of a downturn before the level itself drops. Verified: full suite 834 passed",
    ],
  },
  {
    id: 88, version: "v1.5.0", date: "Jun 23, 2026",
    label: "Hybrid Inference", title: "Automatic Local→Cloud Escalation + Cost Telemetry", color: "#1E5A8A", status: "done",
    summary: "Keeps the local model as the default but escalates hard or low-confidence queries to a cloud model automatically — without the user choosing — and accounts for the spend. Opt-in behind AMAGRA_HYBRID; local-only stays the default.",
    steps: [
      "providers/base.py: GenResult (text + tokens + cost_usd + latency) + estimate_tokens/price_for/estimate_cost; additive generate_detailed() — Anthropic reports exact usage, others char-estimate. Sync generate() hot path unchanged",
      "orchestration/router.py: decide_with_confidence() exposes a calibrated routing-confidence signal (0.95 pin → 0.25 no-match); decide() is now a thin wrapper",
      "providers/policy.py: declarative EscalationPolicy + load_policy() (off by default) + select_provider() — tier gate, budget check, cheap no-network readiness check, fall back to local with a reason",
      "coordinator enhancement gate routes through select_provider(): legacy compound/moderate preserved, hybrid adds low-confidence escalation; smart_llm gained force= + enhance_response_detailed()",
      "run_tracer cost columns (idempotent migration) + record_cost()/cost_summary(); GET /runs/cost; Cognition 'Inference Cost · Productivity' cell — reads '$0.00 fully local' by default",
      "Verified: full suite 865 passed, 35 new hybrid-inference tests across 3 files",
    ],
  },
  {
    id: 89, version: "v1.5.1", date: "Jun 24, 2026",
    label: "Brand & Social Polish", title: "Favicon Raster Set + Social Card", color: "#1E5A8A", status: "done",
    summary: "Rounds out the brand surface: a complete gold AMAGRA favicon set (the SVG plus .ico, apple-touch, and PWA rasters) and a refreshed social-preview / og:image card so shared links look intentional.",
    steps: [
      "Gold 'A' monogram favicon set — favicon.ico (16/32/48/64), favicon-32.png, apple-touch-icon.png, logo192/512.png, generated from icon.svg by tools/gen_brand_assets.py (Pillow, no SVG rasterizer needed)",
      "Refreshed social-preview card + og:image meta so GitHub/social unfurls render the brand",
    ],
  },
  {
    id: 90, version: "v1.5.2", date: "Jun 24, 2026",
    label: "Release Hygiene & Roadmap Runway", title: "v1.6 Workspace Runway + Platform Entity Model", color: "#1E5A8A", status: "done",
    summary: "A non-breaking runway release that clears the path to the v1.6 workspaces milestone: the platform entity model RFC and the v1.5.2/v1.5.3 adoption-floor plan land as records, with version markers reconciled.",
    steps: [
      "docs/ROADMAP.md: v1.5.2/v1.5.3 runway sequenced into the v1.6 workspaces milestone (additive, no schema break)",
      "docs/design/PLATFORM_ENTITY_MODEL.md: the Organization → Project → Workspace entity model RFC for v1.6",
      "Version markers reconciled to v1.5.2 across api.py, package.json, constants.js",
    ],
  },
  {
    id: 91, version: "v1.5.4", date: "Jun 26, 2026",
    label: "Routing Seam & Recall Robustness", title: "Extensible routing + two recall bugs closed", color: "#1E5A8A", status: "done",
    summary: "A correctness + extensibility release. The routing layer gains its extension seam, two latent recall bugs are closed, and the v1.6 foundation lands in docs.",
    steps: [
      "Swappable Router seam over core_brain — orchestration/router_interface.py (Router Protocol, BrainRouter, get_router/set_router), additive (#62)",
      "Context-bleed recall guard — get_memory_context no longer injects a stale quantitative instance of the same template (#63)",
      "Learned-router graceful degradation — 503 on undertrainable corpus, adaptive CV folds, no caching of failed trains (#63)",
      "Signed-stability metrics (curvature alarm, drift lens), eval-rigor doc framing (#20/#61), Prompt-as-Artifact contract (#73), plugin-architecture docs (#60)",
      "Test suite → 914 passing",
    ],
  },
  {
    id: 92, version: "v1.5.5", date: "Jun 28, 2026",
    label: "UI Consolidation & Prompt IDE", title: "Leaner nav, one API seam, a real editor", color: "#7E3F8F", status: "done",
    summary: "A premium UI hardening pass ahead of v1.6: the Runs surface collapses 7 tabs to 4, the backend URL is centralized into one seam, the Prompt IDE moves to Monaco, and the dashboard signals an offline engine instead of failing silently.",
    steps: [
      "Runs surface 7→4 — Trace folded into Decisions (History|Live), Policy moved to Cognition, Replay demoted to a per-decision action",
      "Centralized API base (ui/src/api.js, VITE_API_BASE) — 62 hardcoded localhost sites repointed; the seam v1.6 #69 needs",
      "Premium API-offline banner with start command + working Retry",
      "App.jsx de-monolithed 1,395→1,037 — extracted navConfig.js + Modals.jsx",
      "Monaco-powered Prompt IDE (v1.6 #71 foundation) — bundled locally (no CDN), slim core, lazy-loaded; initial bundle stays ~1.24MB gzip 358KB",
    ],
  },
  {
    id: 93, version: "v1.5.6", date: "Jun 29, 2026",
    label: "Launch Prep & Calibration", title: "Honest comparison, the routing seam on the hot path, calibrated confidence", color: "#1E5A8A", status: "done",
    summary: "A launch-runway release: the messaging source of truth and an honest head-to-head land as durable assets, the Router seam shipped in v1.5.4 is finally on the live path, and confidence scores gain a calibration record so reliability can be measured, not asserted.",
    steps: [
      "POSITIONING.md — single source of messaging truth; honest head-to-head COMPARISON.md vs Open WebUI/LibreChat/AnythingLLM (#82)",
      "Coordinator now routes through get_router().decide() — the Router seam is on the hot path and swappable; stale memory_context.py duplicate removed (#64, #65)",
      "Calibration logging — raw confidence/performance pairs captured with a reliability report (#84)",
    ],
  },
  {
    id: 94, version: "v1.6.0", date: "Jun 29, 2026",
    label: "Prompt-as-Artifact & One-File Install", title: "Prompts become first-class versioned artifacts; Amagra ships as a single download", color: "#7E3F8F", status: "done",
    summary: "Prompts stop being throwaway text in a browser tab. They persist as files, every save is a version, runs and decisions link to the version that produced them, and you can diff versions side by side. Plus the install collapses to a one-file AppImage — no Docker, Node, or Python.",
    steps: [
      "One-file AppImage download — bundled Python + UI, no Docker/Node/Python (v1.5.6 #86)",
      "Jailed /workspace write API (write/mkdir/move/delete) behind the owner-action gate (#68)",
      "Prompts persist as workspace files; Ctrl+S commits an immutable version; one-time localStorage import (#69)",
      "Runs persist beside their prompt; decisions key on prompt_version_id with in-place migration (#70)",
      "Monaco inline diagnostics + click-to-fix + side-by-side version-compare DiffEditor (#71)",
    ],
  },
];

// ── Roadmap (upcoming phases) ──────────────────────────────────────────────────
export const ROADMAP = [
  // ── Engineering debt ──────────────────────────────────────────────────────────
  {
    id: 33, version: "v0.8.3", title: "Contradiction Resolution", color: "#C2410C", status: "done", priority: "medium",
    summary: "Contradictions panel on Cognitive OS tab (list + diff view). Auto-resolve keeps newer memory (higher id) when cos > 0.90. GET/POST /memory/auto-resolve endpoints.",
    items: [
      "Add Contradictions panel to Cognitive OS tab (list + diff view) ✅",
      "Auto-resolve strategy: prefer newer memory when conflict_score > 0.90 ✅",
      "Manual resolve: UI button to accept A, accept B, or merge",
      "Resolved contradictions archived — not deleted (audit trail)",
      "Contradiction rate metric in /memory/stats",
    ],
  },
  {
    id: 34, version: "v0.8.5", title: "FAISS Backend Swap", color: "#1E5A8A", status: "done", priority: "medium",
    summary: "FAISSBackend active at 628 entries. Auto-promote hook triggers at 800. Benchmark: vector search P50 0.38ms (target ≤5ms). New /bench and /promote endpoints. MemoryBackendPanel expanded in DataTab.",
    items: [
      "promote_if_needed() auto-promotes SQLite→FAISS when count ≥ 800 ✅",
      "Vector search P50: 0.38ms at 628 entries — well under 5ms target ✅",
      "GET /analysis/memory_backend — now includes index_ntotal, drift_pct, index_size_mb ✅",
      "GET /analysis/memory_backend/bench — P50/P95 split: vector search vs full pipeline ✅",
      "POST /analysis/memory_backend/promote — manual trigger for SQLite→FAISS ✅",
      "DataTab MemoryBackendPanel — cards for index vectors, drift %, index size, latency ✅",
    ],
  },

  // ── Architecture hardening (30/60/90-day plan from June 2026 review) ─────────
  {
    id: 40, version: "v0.9.2", title: "Security + Architecture Hardening", color: "#B42318", status: "done", priority: "high",
    summary: "7 of 8 confirmed High-severity flaws resolved. F10 (SQLite sprawl) deferred to v0.9.3. All other Phase 38 stability + observability improvements shipped.",
    items: [
      "F1: /admin/keys removed from _PUBLIC_PATHS — ADMIN_TOKEN env guard added ✅",
      "F7: {user_profile} format bug fixed in python_dev, it_networking, ai_ml ✅",
      "F2: agents/registry.py — canonical agent registry, 20-file blazor→dotnet rename, boot assertion ✅",
      "F4: run_id column on brain_decisions — direct session↔decision join, time-window race eliminated ✅",
      "F6: Keyword-triggered RCE removed from python_dev.py — path allowlist added ✅",
      "F8: Contradiction detector false-positives — content-word overlap, threshold 0.20→0.35 ✅",
      "F5: _critic_perf from grounded_evaluate() replaces hardcoded proxy (0.75/0.55) as learning signal ✅",
      "F10: Consolidate 8 SQLite databases → single amagra.db with versioned migrations — deferred to v0.9.3 (~10h)",
    ],
  },
  {
    id: 45, version: "v0.9.3", title: "Threading + Eval Integrity", color: "#9A6C00", status: "done", priority: "high",
    summary: "All four v0.9 audit phases shipped: security hardening, async/concurrency, memory surface + multi-provider, luxury UI + brand. Release Notes tab wired, Progress tab updated.",
    items: [
      "F10: Consolidate 8 SQLite databases → single amagra.db with versioned schema migrations (~10h)",
      "threads + turns tables — session_id on /ask, rolling context window (last 4-6 turns) (~8h)",
      "ChatTab thread rail — per-thread history, thread selector, new thread button (~6h)",
      "Routing telemetry: log query → agent + was_correct signal → GET /telemetry/routing (~4h)",
      "Eval integrity split: curated-eval (138 queries) vs telemetry-eval (real queries) tracked separately (~3h)",
      "README pitch rewrite: outcomes-first (10–30s latency reduction, not routing architecture), benchmark caveat explicit (~2h)",
    ],
  },
  {
    id: 60, version: "v0.10.1", title: "RAG File Context", color: "#C48808", status: "done", priority: "high",
    summary: "Users can attach files (PDF, Markdown, code) in chat. Chunks are embedded into the existing FAISS/SQLite memory layer with mem_type='document'. Top-k chunks injected into both /ask and /ask/stream before the LLM sees the query.",
    items: [
      "POST /documents/upload — multipart upload, text extraction, RecursiveCharacterTextSplitter (800c/100 overlap), FAISS embed ✅",
      "GET /documents — list stored files with chunk counts ✅",
      "DELETE /documents/{filename} — delete all chunks for a file ✅",
      "AskRequest.context_files: list[str] — filenames to pull context from ✅",
      "_get_document_context() — cosine search over document chunks, injected into task message ✅",
      "Both /ask and /ask/stream inject document context when context_files provided ✅",
      "ChatTab: ⊕ attach button, file chips with upload/ready/error states, context_files in send payload ✅",
      "Re-upload is idempotent — old chunks deleted before inserting new ones ✅",
    ],
  },
  {
    id: 61, version: "v1.0.1", title: "Launch Polish & Hardening", color: "#0F766E", status: "done", priority: "high",
    summary: "Post-1.0.0 hardening shipped: a lean runtime core under the router, first-run onboarding, the Vite migration, and a centralized SQLite path registry. Test suite 544 → 624. Public launch (Show HN / self-host catalogs) is the one residual item.",
    items: [
      "Lean runtime core — Context/Result spine, onion middleware, lazy registry, append-only run log ✅",
      "Delta-algebra routing seam — frozen dispatch reducer, router score/decide split ✅",
      "In-product onboarding — first-run flow, Ollama + model-pull detection, guided first prompt ✅",
      "Vite migration — retired CRA (unmaintained, React 19 instability) ✅",
      "DB path registry — infrastructure/db.py centralizes SQLite paths (seam toward single amagra.db) ✅",
      "Test suite 544 → 624 passing ✅",
      "Launch prep — Show HN, r/LocalLLaMA, Docker Hub, Unraid/Umbrel template, Homebrew formula (pending)",
    ],
  },
  {
    id: 41, version: "v1.1.0", title: "Tool-Using Agents", color: "#0F766E", status: "done", priority: "high",
    summary: "Agents gain real capabilities, not just text: jailed file access, sandboxed code execution, and live web search. The biggest quality jump available without swapping the model. All capabilities + the structured tool loop shipped; remaining polish is auto-invoking the loop inside the default chat flow. (SSE streaming shipped in 1.0.0.)",
    items: [
      "Memory import/export — JSON / Markdown round-trip ✅",
      "Thread management: rename, fork, archive ✅",
      "tools/workspace.py — read, list, search with Path.resolve().is_relative_to(root) jail ✅",
      "tools/sandbox.py — resource.setrlimit CPU/AS, scrubbed env, python3 -I isolation (opt-in via AMAGRA_SANDBOX) ✅",
      "Stop / regenerate / edit-message affordances in ChatTab ✅",
      "tools/web.py — SearXNG self-hosted (default, no key) + Brave/Tavily; GET /search/web ✅",
      "Structured tool loop: JSON action → execute → observe, max N iters; tools/tool_loop.py + POST /tools/run ✅",
      "Tool calls logged → event_bus (tool.call events) ✅",
      "Auto-invoke the tool loop inside the default specialist-agent chat flow (polish)",
    ],
  },
  {
    id: 94, version: "v1.6.0", title: "Prompt-as-Artifact Foundation", color: "#7E3F8F", status: "done", priority: "high",
    summary: "The keystone of the Prompt-IDE pivot (epic #67): prompts become first-class, versioned files instead of throwaway browser text — runs and decisions link to the version that produced them, and versions diff side by side.",
    items: [
      "Jailed /workspace write API (write/mkdir/move/delete) behind the owner-action gate (#68) ✅",
      "Prompts persist as files; Ctrl+S commits a version; one-time localStorage import (#69) ✅",
      "Runs persist beside their prompt; decisions key on prompt_version_id + migration (#70) ✅",
      "Monaco inline diagnostics + click-to-fix + version-compare DiffEditor (#71) ✅",
    ],
  },
  {
    id: 42, version: "v1.6", title: "Workspaces & RBAC", color: "#C2410C", status: "next", priority: "high",
    summary: "The remaining v1.6 work after the Prompt-as-Artifact foundation shipped (v1.6.0): multiple isolated projects per user, role-based access, and a custom agent builder.",
    items: [
      "workspaces table — multiple isolated projects per user, per-workspace memory namespace (8h)",
      "RBAC — owner / admin / member roles, enforced at the route layer (6h)",
      "Custom agent builder — name, system prompt, keyword triggers via admin UI, no code deploy (8h)",
      "Workspace switcher in nav — active-workspace ContextVar threads through routing + memory (4h)",
      "Per-workspace settings — default provider, enabled agents, routing preferences (4h)",
    ],
  },
  {
    id: 43, version: "v1.5.0", title: "Hybrid Inference", color: "#1E5A8A", status: "done", priority: "medium",
    summary: "Runtime provider/model switching shipped in v1.2.0 (Model Choice) and cross-model comparison in v1.3.0 (Debugger). v1.5.0 adds the automatic policy: keep local default, but escalate compound or low-confidence queries to a cloud model without the user choosing — opt-in behind AMAGRA_HYBRID, with cost surfaced on the dashboard.",
    items: [
      "LLMProvider protocol + GenResult (cost_usd/tokens/latency) — generate_detailed(), exact usage from Anthropic ✅",
      "Declarative EscalationPolicy + load_policy() — default=local-fast, compound→cloud, confidence_below:0.6→cloud (off by default) ✅",
      "select_provider(confidence, complexity, tier) — tier gate, budget check, cheap readiness check, fallback chain ✅",
      "decide_with_confidence() routing signal; coordinator enhancement gate routes through select_provider (flag-gated, local default) ✅",
      "cost_usd → runs traces → GET /runs/cost → Cognition 'Inference Cost' Productivity cell ✅",
    ],
  },
  {
    id: 46, version: "v1.7.0", title: "Team Memory & Governance", color: "#15803D", status: "planned", priority: "medium",
    summary: "The moment two users share a memory pool is the moment there's a moat no chat UI can copy. Shared team memory plus the governance surface enterprises require — every AI decision logged, explainable, and exportable, on hardware they control.",
    items: [
      "Shared team memory — per-workspace FAISS index, opt-in pooling across a team's keys (10h)",
      "Admin console — user management, key provisioning, per-workspace settings (6h)",
      "Audit-log export + Chain-of-Authorization (CoA) — structured who/what/why/ts/decision_id record on every data-modifying action; exportable as signed JSONL (8h)",
      "SSO / SAML integration (6h)",
      "Configurable data-retention policies — per-workspace TTL (4h)",
      "Encrypted cross-machine memory sync/backup (6h)",
      "Air-gapped installer — fully offline provisioning (5h)",
    ],
  },
  {
    id: 44, version: "v1.4.0", title: "Unified Workspace UI — ~26 Views → 6", color: "#7E3F8F", status: "done", priority: "medium",
    summary: "The dashboard was 5 top-level surfaces (Chat · Library · Memory · Inspect · Settings) fronting ~26 view components. Consolidated into 6 coherent views with observability as the hero screen. Nothing deleted — reorganized into hierarchy.",
    items: [
      "6 primary views: Workspace · Runs · Cognition · Memory · Research · Settings ✅",
      "Single data-driven nav model (SURFACES) — sidebar + SubNav + last-tab memory derived from one source; per-surface descriptions ✅",
      "Cognition: UCI · Risk · Events · Plan in one dashboard grid (CognitionView) ✅",
      "Runs: facet sub-tabs — Overview · Runs · Decisions · Trace · Inspector · Policy · Replay ✅ (run-scoped master-detail deferred to v1.4.1)",
      "Monaco code pane: read + edit + DiffEditor version compare ✅ (#71); workspace write API behind owner gate ✅ (#68)",
      "Extract inline style tokens to theme.js — deferred to a polish pass",
    ],
  },
  {
    id: 47, version: "v2.0.0", title: "Agent Registry & SDK", color: "#7E3F8F", status: "planned", priority: "medium",
    summary: "Agents become portable artifacts; the runtime stays the product. A manifest-declared agent automatically joins routing, memory retrieval, the critic gate, and step verification — extensibility without compromising runtime quality.",
    items: [
      "Agent SDK — manifest-declared agents (id, skills, keywords, routing_examples, confidence_threshold) (12h)",
      "Importable agent packs — export/import as YAML or ZIP (4h)",
      "Curated registry — Official / Verified community / Local trust tiers (8h)",
      "Registered agents auto-participate in routing, telemetry, memory, critic gate, step verification (6h)",
      "Standalone environment — the execution graph as the interface (8h)",
    ],
  },
];

// ── Version epoch groups (used by VersionHistoryTab) ──────────────────────────
export const VERSION_EPOCHS = [
  { version: "v1.7.0", label: "Cross-Platform Desktop App", color: "#7E3F8F", phases: [97] },
  { version: "v1.6.4", label: "System Alignment & Honesty Pass", color: "#1E5A8A", phases: [96] },
  { version: "v1.6.3", label: "Desktop App & Unified Launcher", color: "#7E3F8F", phases: [95] },
  { version: "v1.6.0", label: "Prompt-as-Artifact & One-File Install", color: "#7E3F8F", phases: [94] },
  { version: "v1.5.6", label: "Launch Prep & Calibration", color: "#1E5A8A", phases: [93] },
  { version: "v1.5.5", label: "UI Consolidation & Prompt IDE", color: "#7E3F8F", phases: [92] },
  { version: "v1.5.4", label: "Routing Seam & Recall Robustness", color: "#1E5A8A", phases: [91] },
  { version: "v1.5.2", label: "Release Hygiene & Runway", color: "#1E5A8A", phases: [90] },
  { version: "v1.5.1", label: "Brand & Social Polish",    color: "#1E5A8A", phases: [89] },
  { version: "v1.5.0", label: "Hybrid Inference",        color: "#1E5A8A", phases: [88] },
  { version: "v1.4.6", label: "OCAC Stability Metrics", color: "#7E3F8F", phases: [87] },
  { version: "v1.4.5", label: "Observability & Favicon Fix", color: "#7E3F8F", phases: [86] },
  { version: "v1.4.4", label: "Single Gold Favicon",     color: "#7E3F8F", phases: [85] },
  { version: "v1.4.3", label: "Card & Layout Refinement", color: "#7E3F8F", phases: [84] },
  { version: "v1.4.2", label: "Gold Refinement",        color: "#7E3F8F",  phases: [83] },
  { version: "v1.4.1", label: "UI Refinement",          color: "#7E3F8F",  phases: [82] },
  { version: "v1.4.0", label: "Unified Workspace UI",   color: "#7E3F8F",  phases: [81] },
  { version: "v1.3.1", label: "Debugger Divergence",    color: "#C48808",  phases: [80] },
  { version: "v1.3.0", label: "Cross-Model Debugger",   color: "#C48808",  phases: [79] },
  { version: "v1.2.0", label: "Model Choice & Desktop", color: "#15803D",  phases: [78] },
  { version: "v1.1.2", label: "Eval Rigor & Security", color: "#15803D",  phases: [77] },
  { version: "v1.1.1", label: "Tools in Default Path", color: "#15803D",  phases: [76] },
  { version: "v1.1.0", label: "Tool-Using Agents",    color: "#15803D",  phases: [75] },
  { version: "v1.0.0", label: "First Public Release", color: "#15803D",  phases: [70, 71, 72, 73, 74] },
  { version: "v0.10", label: "Content & Launch",      color: "#C48808",  phases: [60] },
  { version: "v0.9", label: "Commercialization",      color: "#C2410C",  phases: [36, 37, 38, 39, 50, 51, 52, 53] },
  { version: "v0.8", label: "Loop Activation",        color: "#15803D",  phases: [30, 31, 32, 33, 34, 35] },
  { version: "v0.7", label: "Refinement & UI",        color: "#0F766E",  phases: [25, 26, 27, 28, 29] },
  { version: "v0.6", label: "Reflection System",     color: "#7E3F8F",  phases: [19, 20, 21, 22, 23, 24] },
  { version: "v0.5", label: "Memory Intelligence",   color: "#C2410C",  phases: [13, 14, 15, 16, 17, 18] },
  { version: "v0.4", label: "Optimization & Routing",color: "#047857",  phases: [10, 11, 12] },
  { version: "v0.3", label: "Integration",           color: "#0E7490",  phases: [7,  8,  9] },
  { version: "v0.2", label: "Core Systems",          color: "#9A6C00",  phases: [4,  5,  6] },
  { version: "v0.1", label: "Foundation",            color: "#15803D",  phases: [1,  2,  3] },
];

export const PROGRESS_STEPS = [
  "◈ Coordinator analyzing…",
  "⊹ Consulting agent registry…",
  "∴ Routing to specialist…",
  "⚙ Agent processing…",
  "∑ Gathering context…",
  "· Generating response…",
];

export const AGENT_ID_REVERSE = {
  it_networking:      "it_networking",
  python_dev:         "python_dev",
  dotnet_dev:         "dotnet_dev",
  ai_ml:              "ai_ml",
  knowledge_learning: "knowledge_learning",
  terse:              "terse",
  coordinator:        "coordinator",
};

// ── User-facing promises / long-term commitments ──────────────────────────────
// DEPRECATED (v1.7.1): the Promises tab was retired — it duplicated Releases,
// which already renders ROADMAP upcoming (the open pledges) + BUILD_PHASES history
// (the delivered ones). Kept here as the source record / for a possible landing
// sync; no longer surfaced in the app menu.
// status: "delivered" | "building" | "committed"
// category: "Performance" | "AI" | "Developer" | "Platform" | "Privacy"

export const PROMISES = [
  // ── Delivered ────────────────────────────────────────────────────────────────
  {
    id: 1,
    icon: "⊓",
    title: "100% Local — Your Data Never Leaves",
    description: "Every inference, memory retrieval, and decision happens on your machine. No telemetry, no cloud calls, no data sharing. Verifiable by reading the source.",
    category: "Privacy",
    status: "delivered",
    delivered_on: "2026-01-01",
    priority: "high",
  },
  {
    id: 2,
    icon: "⚖",
    title: "Full Source, MIT Licensed",
    description: "The entire codebase is open under MIT. Fork it, self-host it, modify it. You will never be locked into a hosted version.",
    category: "Platform",
    status: "delivered",
    delivered_on: "2026-05-01",
    priority: "high",
  },
  {
    id: 3,
    icon: "§",
    title: "10 Specialist Agents at Launch",
    description: "Python, .NET, Web, DevOps, Data, AI/ML, IT Networking, Writer, Knowledge, and Terse — each with domain-tuned prompts, keywords, and per-agent memory.",
    category: "AI",
    status: "delivered",
    delivered_on: "2026-06-01",
    priority: "high",
  },
  {
    id: 4,
    icon: "◈",
    title: "Persistent Semantic Memory",
    description: "Every useful exchange is remembered. FAISS vector search with nomic-embed-text finds relevant context in under 1ms. Memory survives restarts.",
    category: "AI",
    status: "delivered",
    delivered_on: "2026-05-01",
    priority: "high",
  },
  {
    id: 5,
    icon: "↗",
    title: "Conversation Threading",
    description: "Each conversation thread keeps its context. Switch between projects without starting over — the agent remembers the last 4 turns of every thread.",
    category: "AI",
    status: "delivered",
    delivered_on: "2026-06-11",
    priority: "high",
  },

  // ── Currently Building ────────────────────────────────────────────────────────
  {
    id: 6,
    icon: "→",
    title: "Streaming Responses",
    description: "First token in under 2 seconds instead of a 30-second wait. Watch the agent think and write in real time.",
    category: "Performance",
    status: "delivered",
    delivered_on: "2026-06-12",
    priority: "high",
  },
  {
    id: 7,
    icon: "▤",
    title: "File and Folder Context",
    description: "Drop a file or directory into the chat. Agents read and reason over your actual codebase — not a description of it. RAG file upload plus a jailed read/list/search tool (GET /workspace/*).",
    category: "Developer",
    status: "delivered",
    delivered_on: "2026-06-14",
    priority: "high",
  },

  // ── Building ─────────────────────────────────────────────────────────────────
  {
    id: 8,
    icon: "▶",
    title: "Sandboxed Code Execution",
    description: "Run code in an isolated sandbox with CPU and memory limits, and see the output. POST /sandbox/run (opt-in via AMAGRA_SANDBOX); autonomous in-agent execution lands with the tool loop.",
    category: "Developer",
    status: "delivered",
    delivered_on: "2026-06-14",
    priority: "high",
  },
  {
    id: 9,
    icon: "⊹",
    title: "Live Web Search",
    description: "Search the web when a question needs up-to-date information — docs, changelogs, errors. Self-hosted SearXNG by default; opt-in Brave/Tavily. GET /search/web.",
    category: "AI",
    status: "delivered",
    delivered_on: "2026-06-14",
    priority: "high",
  },
  {
    id: 10,
    icon: "◑",
    title: "Multiple LLM Backends",
    description: "Choose your own model: Claude, GPT-4o, Gemini, Llama 3, Mistral, Gemma. Swap the inference backend without touching your agents or memory.",
    category: "Platform",
    status: "delivered",
    delivered_on: "2026-06-17",
    priority: "medium",
  },
  {
    id: 11,
    icon: "✎",
    title: "Custom Agent Builder",
    description: "Define your own specialist agent via the admin UI — give it a name, system prompt, and keyword triggers. No code deployment required.",
    category: "Platform",
    status: "committed",
    target: "v1.6",
    target_quarter: "Q1 2027",
    priority: "medium",
  },
  {
    id: 12,
    icon: "⊢",
    title: "Amagra as a Standalone Environment",
    description: "Amagra will not become a plugin for someone else's tool. The goal is a purpose-built environment where the execution graph, agents, and memory are the interface — not a text editor with a chat panel bolted on.",
    category: "Platform",
    status: "committed",
    target: "v2.0",
    target_quarter: "2027",
    priority: "high",
  },
  {
    id: 13,
    icon: "⬡",
    title: "Team Shared Memory",
    description: "Your whole team shares one knowledge base. Ask a question answered by a colleague last week — the agent already knows the answer.",
    category: "Platform",
    status: "committed",
    target: "v1.7",
    target_quarter: "Q1 2027",
    priority: "medium",
  },
  {
    id: 14,
    icon: "◷",
    title: "No Regressions Guarantee",
    description: "Every release runs the full eval suite before shipping — 889 tests on the latest. Routing accuracy, response quality, and latency benchmarks are published in the release notes.",
    category: "Performance",
    status: "delivered",
    delivered_on: "2026-06-25",
    priority: "high",
  },
  {
    id: 15,
    icon: "⊕",
    title: "Hybrid Inference — Local by Default, Cloud When It Counts",
    description: "Stay fully local for everyday work, and let hard or low-confidence queries escalate to a cloud model automatically — with the spend accounted for. Opt-in; local-only stays the default.",
    category: "AI",
    status: "delivered",
    delivered_on: "2026-06-23",
    priority: "high",
  },
  {
    id: 16,
    icon: "◎",
    title: "Cross-Model Consensus",
    description: "When an answer matters, ask several models at once and see how much they actually agree — an agreement score, the most representative answer, and named dissenters, with the full comparison shown. Verify before you trust.",
    category: "AI",
    status: "delivered",
    delivered_on: "2026-06-25",
    priority: "high",
  },
  {
    id: 17,
    icon: "⌘",
    title: "Versioned Prompts",
    description: "Your prompts are first-class artifacts, not throwaway text. They persist as files on your machine, every save is an immutable version, the model run and the decision you made link to the exact version that produced them, and you can diff any two versions side by side.",
    category: "Platform",
    status: "delivered",
    delivered_on: "2026-06-29",
    priority: "high",
  },
];
